package com.agridata.cdzhdj.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.agridata.cdzhdj.data.HarmlessAnimalBean;
import com.agridata.cdzhdj.data.TRegion;

import com.agridata.cdzhdj.dao.HarmlessAnimalBeanDao;
import com.agridata.cdzhdj.dao.TRegionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig harmlessAnimalBeanDaoConfig;
    private final DaoConfig tRegionDaoConfig;

    private final HarmlessAnimalBeanDao harmlessAnimalBeanDao;
    private final TRegionDao tRegionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        harmlessAnimalBeanDaoConfig = daoConfigMap.get(HarmlessAnimalBeanDao.class).clone();
        harmlessAnimalBeanDaoConfig.initIdentityScope(type);

        tRegionDaoConfig = daoConfigMap.get(TRegionDao.class).clone();
        tRegionDaoConfig.initIdentityScope(type);

        harmlessAnimalBeanDao = new HarmlessAnimalBeanDao(harmlessAnimalBeanDaoConfig, this);
        tRegionDao = new TRegionDao(tRegionDaoConfig, this);

        registerDao(HarmlessAnimalBean.class, harmlessAnimalBeanDao);
        registerDao(TRegion.class, tRegionDao);
    }
    
    public void clear() {
        harmlessAnimalBeanDaoConfig.clearIdentityScope();
        tRegionDaoConfig.clearIdentityScope();
    }

    public HarmlessAnimalBeanDao getHarmlessAnimalBeanDao() {
        return harmlessAnimalBeanDao;
    }

    public TRegionDao getTRegionDao() {
        return tRegionDao;
    }

}
